### PR TITLE
Feature v1

### PR DESCRIPTION
**Pull request by Calyhre**
# Roadmap for the first stable release

Based on [developer.dribbble.com/v1](http://developer.dribbble.com/v1/) endpoints.

## [Buckets](http://developer.dribbble.com/v1/buckets/)
* [x] ~~Get a bucket~~
* [x] ~~Create a bucket~~
* [x] ~~Update a bucket~~
* [x] ~~Delete a bucket~~

#### [Shots](http://developer.dribbble.com/v1/buckets/shots/)
* [x] ~~List shots for a bucket~~
* [x] ~~Add a shot to a bucket~~
* [x] ~~Remove a shot from a bucket~~

## [Projects](http://developer.dribbble.com/v1/projects/)
* [x] ~~Get a project~~

#### [Shots](http://developer.dribbble.com/v1/projects/shots/)
* [x] ~~List shots for a project~~

## [Shots](http://developer.dribbble.com/v1/shots/)
* [x] ~~List shots~~
* [x] ~~Get a shot~~
* [x] ~~Create a shot~~
* [x] ~~Update a shot~~
* [x] ~~Delete a shot~~

#### [Attachments](http://developer.dribbble.com/v1/shots/attachments/)
* [x] ~~List attachments for a shot~~
* [x] ~~Create an attachment~~
* [x] ~~Get a single attachmen~~
* [x] ~~Delete an attachment~~

#### [Buckets](http://developer.dribbble.com/v1/shots/buckets/)
* [x] ~~List buckets for a shot~~

#### [Comments](http://developer.dribbble.com/v1/shots/comments/)
* [x] ~~List comments for a shot~~
* [x] ~~List likes for a comment~~
* [x] ~~Create a comment~~
* [x] ~~Get a single comment~~
* [x] ~~Update a comment~~
* [x] ~~Delete a comment~~
* [x] ~~Check if you like a comment~~
* [x] ~~Like a comment~~
* [x] ~~Unlike a comment~~

#### [Likes](http://developer.dribbble.com/v1/shots/likes/)
* [x] ~~List the likes for a shot~~
* [x] ~~Check if you like a shot~~
* [x] ~~Like a shot~~
* [x] ~~Unlike a shot~~

#### [Projects](http://developer.dribbble.com/v1/shots/projects/)
* [x] ~~List projects for a shot~~

#### [Rebounds](http://developer.dribbble.com/v1/shots/rebounds/)
* [x] ~~List rebounds for a shot~~

#### [Members](http://developer.dribbble.com/v1/teams/members/)
* [x] ~~List a team’s members~~

#### [Shots](http://developer.dribbble.com/v1/teams/shots/)
* [x] ~~List shots for a team~~

## [Users](http://developer.dribbble.com/v1/users/)
* [x] ~~Get a single user~~
* [x] ~~Get the authenticated user~~

#### [Buckets](http://developer.dribbble.com/v1/users/buckets/)
* [x] ~~List a user’s buckets~~
* [x] ~~List authenticated user’s buckets~~

#### [Followers](http://developer.dribbble.com/v1/users/followers/)
* [x] ~~List followers of a user~~
* [x] ~~List followers of authenticated user~~
* [x] ~~List users followed by a user~~
* [x] ~~List shots for users followed by a user~~
* [x] ~~Check if you are following a user~~
* [x] ~~Check if one user is following another~~
* [x] ~~Follow a user~~
* [x] ~~Unfollow a user~~

#### [Likes](http://developer.dribbble.com/v1/users/likes/)
* [x] ~~List shot likes for a user~~
* [x] ~~List shot likes for authenticated user~~

#### [Projects](http://developer.dribbble.com/v1/users/projects/)
* [x] ~~List a user’s projects~~
* [x] ~~List authenticated user’s projects~~

#### [Shots](http://developer.dribbble.com/v1/users/shots/)
* [x] ~~List shots for a user~~
* [x] ~~List shots for authenticated user~~

#### [Teams](http://developer.dribbble.com/v1/users/teams/)
* [x] ~~List a user’s teams~~
* [x] ~~List authenticated user’s teams~~

## Annexes
* [x] Documentation

### CODE REVIEW

**Comment by dustincoates** [comment]
@Calyhre Is this still being worked on or could you use some help with it?

**Comment by Calyhre** [comment]
Hi @dustincoates, as you see, it remains only the like stuff for the comments and the doc.
Everything else is done.

**Comment by dustincoates** [comment]
@Calyhre I did see that. Your response doesn't quite answer my question as to whether you would like help with finishing stuff like the comments and the doc, so I'm going to assume you'd prefer to handle it on your own. :smiley:

**Comment by Calyhre** [comment]
Wow sorry for my evasive answer, any help would be great !
But first, as this is my first Gem, a code review could be a good start I guess.

Also, why not releasing a `.beta2` for people who need it now?
For information, [Drubbbler](https://drubbbler.com) is running on beta1 :)

**Comment by icco** [comment]
My moodboard also uses beta1: https://github.com/icco/inspiration

**Comment by Calyhre** [comment]
Amazing! Let me know if you have question/problem :)

**Pull request merged**
